In [1]:
import pandas as pd

In [2]:
dataset=pd.read_csv("50_Startups_dataset.csv")

In [3]:
dataset

,Unnamed: 0,R&D Spend,Administration,Marketing Spend,State,Profit
0,0,165349.30,136897.90,471784.20,New York,192261.93
1,1,162597.80,151377.69,443898.63,California,191792.16
2,2,153441.61,101145.65,407934.64,Florida,191050.49
3,3,144372.51,118671.95,383199.72,New York,182902.09
4,4,142107.44,91391.87,366168.52,Florida,166188.04
5,5,131877.00,99814.81,362861.46,New York,156991.22
6,6,134615.56,147198.97,127716.92,California,156122.61
7,7,130298.23,145530.16,323876.78,Florida,155752.70
8,8,120542.62,148719.05,311613.39,New York,152211.87
9,9,123334.98,108679.27,304981.72,California,149760.06
10,10,101913.18,110594.21,229161.05,Florida,146122.05
11,11,100672.06,91790.71,249744.65,California,144259.50
12,12,93863.85,127320.48,249839.54,Florida,141585.62
13,13,91992.49,135495.17,252665.03,California,134307.45
14,14,119943.34,156547.52,256513.02,Florida,132602.75
15,15,114523.71,122616.94,261776.33,New York,129917.14
16,16,78013.21,121597.65,264346.16,California,126993.03
17,17,94657.26,145077.68,282574.41,New York,125370.47
18,18,91749.26,114175.89,294919.67,Florida,124267.00
19,19,86419.80,153514.21,0.10,New York,122776.96
20,20,76253.96,113867.40,298664.57,California,118474.13
21,21,78389.57,153773.53,299737.39,New York,111313.12
22,22,73994.66,122782.85,303319.36,Florida,110352.35
23,23,67532.63,105751.13,304768.83,Florida,108734.09
24,24,77044.11,99281.44,140574.91,New York,108552.14
25,25,64664.81,139553.26,137962.72,California,107404.44
26,26,75328.97,144136.08,134050.17,Florida,105733.64
27,27,72107.70,127864.65,353183.91,New York,105008.41
28,28,66051.62,182645.66,118148.30,Florida,103282.48
29,29,65605.58,153032.16,107138.48,New York,101004.74
30,30,61994.58,115641.38,91131.34,Florida,99937.69
31,31,61136.48,152702.02,88218.33,New York,97483.66
32,32,63408.96,129219.71,46085.35,California,97427.94
33,33,55494.05,103057.59,214634.91,Florida,96779.02
34,34,46426.17,157694.02,210797.77,California,96712.90
35,35,46014.12,85047.54,205517.74,New York,96479.61
36,36,28663.86,127056.31,201126.92,Florida,90708.29
37,37,44070.05,51283.24,197029.52,California,89949.24
38,38,20229.69,65948.03,185265.20,New York,81229.16
39,39,38558.61,82982.19,174999.40,California,81005.86
40,40,28754.43,118546.15,172795.77,California,78240.01
41,41,27893.02,84710.87,164470.81,Florida,77798.93
42,42,23641.03,96189.73,148001.21,California,71498.59
43,43,15505.83,127382.40,35534.27,New York,69759.08
44,44,22177.84,154806.24,28334.82,California,65200.43
45,45,1000.33,124153.14,1904.03,New York,64926.18
46,46,1315.56,115816.31,297114.56,Florida,49490.85
47,47,0.10,135427.02,0.10,California,42559.83
48,48,542.15,51743.25,0.10,New York,35673.51
49,49,0.10,116983.90,45173.16,California,14681.50

In [4]:
dataset=dataset.drop(columns=['Unnamed: 0'])

In [5]:
dataset

    R&D Spend  Administration  Marketing Spend       State     Profit
0   165349.30       136897.90        471784.20    New York  192261.93
1   162597.80       151377.69        443898.63  California  191792.16
2   153441.61       101145.65        407934.64     Florida  191050.49
3   144372.51       118671.95        383199.72    New York  182902.09
4   142107.44        91391.87        366168.52     Florida  166188.04
5   131877.00        99814.81        362861.46    New York  156991.22
6   134615.56       147198.97        127716.92  California  156122.61
7   130298.23       145530.16        323876.78     Florida  155752.70
8   120542.62       148719.05        311613.39    New York  152211.87
9   123334.98       108679.27        304981.72  California  149760.06
10  101913.18       110594.21        229161.05     Florida  146122.05
11  100672.06        91790.71        249744.65  California  144259.50
12   93863.85       127320.48        249839.54     Florida  141585.62
13   91992.49       135495.17        252665.03  California  134307.45
14  119943.34       156547.52        256513.02     Florida  132602.75
15  114523.71       122616.94        261776.33    New York  129917.14
16   78013.21       121597.65        264346.16  California  126993.03
17   94657.26       145077.68        282574.41    New York  125370.47
18   91749.26       114175.89        294919.67     Florida  124267.00
19   86419.80       153514.21             0.10    New York  122776.96
20   76253.96       113867.40        298664.57  California  118474.13
21   78389.57       153773.53        299737.39    New York  111313.12
22   73994.66       122782.85        303319.36     Florida  110352.35
23   67532.63       105751.13        304768.83     Florida  108734.09
24   77044.11        99281.44        140574.91    New York  108552.14
25   64664.81       139553.26        137962.72  California  107404.44
26   75328.97       144136.08        134050.17     Florida  105733.64
27   72107.70       127864.65        353183.91    New York  105008.41
28   66051.62       182645.66        118148.30     Florida  103282.48
29   65605.58       153032.16        107138.48    New York  101004.74
30   61994.58       115641.38         91131.34     Florida   99937.69
31   61136.48       152702.02         88218.33    New York   97483.66
32   63408.96       129219.71         46085.35  California   97427.94
33   55494.05       103057.59        214634.91     Florida   96779.02
34   46426.17       157694.02        210797.77  California   96712.90
35   46014.12        85047.54        205517.74    New York   96479.61
36   28663.86       127056.31        201126.92     Florida   90708.29
37   44070.05        51283.24        197029.52  California   89949.24
38   20229.69        65948.03        185265.20    New York   81229.16
39   38558.61        82982.19        174999.40  California   81005.86
40   28754.43       118546.15        172795.77  California   78240.01
41   27893.02        84710.87        164470.81     Florida   77798.93
42   23641.03        96189.73        148001.21  California   71498.59
43   15505.83       127382.40         35534.27    New York   69759.08
44   22177.84       154806.24         28334.82  California   65200.43
45    1000.33       124153.14          1904.03    New York   64926.18
46    1315.56       115816.31        297114.56     Florida   49490.85
47       0.10       135427.02             0.10  California   42559.83
48     542.15        51743.25             0.10    New York   35673.51
49       0.10       116983.90         45173.16  California   14681.50

In [6]:
dataset.columns

Index(['R&D Spend', 'Administration', 'Marketing Spend', 'State', 'Profit'], dtype='object')

In [7]:
dataset=pd.get_dummies(dataset,drop_first=True)

In [8]:
dataset

,R&D Spend,Administration,Marketing Spend,Profit,State_Florida,State_New York
0,165349.30,136897.90,471784.20,192261.93,False,True
1,162597.80,151377.69,443898.63,191792.16,False,False
2,153441.61,101145.65,407934.64,191050.49,True,False
3,144372.51,118671.95,383199.72,182902.09,False,True
4,142107.44,91391.87,366168.52,166188.04,True,False
5,131877.00,99814.81,362861.46,156991.22,False,True
6,134615.56,147198.97,127716.92,156122.61,False,False
7,130298.23,145530.16,323876.78,155752.70,True,False
8,120542.62,148719.05,311613.39,152211.87,False,True
9,123334.98,108679.27,304981.72,149760.06,False,False
10,101913.18,110594.21,229161.05,146122.05,True,False
11,100672.06,91790.71,249744.65,144259.50,False,False
12,93863.85,127320.48,249839.54,141585.62,True,False
13,91992.49,135495.17,252665.03,134307.45,False,False
14,119943.34,156547.52,256513.02,132602.75,True,False
15,114523.71,122616.94,261776.33,129917.14,False,True
16,78013.21,121597.65,264346.16,126993.03,False,False
17,94657.26,145077.68,282574.41,125370.47,False,True
18,91749.26,114175.89,294919.67,124267.00,True,False
19,86419.80,153514.21,0.10,122776.96,False,True
20,76253.96,113867.40,298664.57,118474.13,False,False
21,78389.57,153773.53,299737.39,111313.12,False,True
22,73994.66,122782.85,303319.36,110352.35,True,False
23,67532.63,105751.13,304768.83,108734.09,True,False
24,77044.11,99281.44,140574.91,108552.14,False,True
25,64664.81,139553.26,137962.72,107404.44,False,False
26,75328.97,144136.08,134050.17,105733.64,True,False
27,72107.70,127864.65,353183.91,105008.41,False,True
28,66051.62,182645.66,118148.30,103282.48,True,False
29,65605.58,153032.16,107138.48,101004.74,False,True
30,61994.58,115641.38,91131.34,99937.69,True,False
31,61136.48,152702.02,88218.33,97483.66,False,True
32,63408.96,129219.71,46085.35,97427.94,False,False
33,55494.05,103057.59,214634.91,96779.02,True,False
34,46426.17,157694.02,210797.77,96712.90,False,False
35,46014.12,85047.54,205517.74,96479.61,False,True
36,28663.86,127056.31,201126.92,90708.29,True,False
37,44070.05,51283.24,197029.52,89949.24,False,False
38,20229.69,65948.03,185265.20,81229.16,False,True
39,38558.61,82982.19,174999.40,81005.86,False,False
40,28754.43,118546.15,172795.77,78240.01,False,False
41,27893.02,84710.87,164470.81,77798.93,True,False
42,23641.03,96189.73,148001.21,71498.59,False,False
43,15505.83,127382.40,35534.27,69759.08,False,True
44,22177.84,154806.24,28334.82,65200.43,False,False
45,1000.33,124153.14,1904.03,64926.18,False,True
46,1315.56,115816.31,297114.56,49490.85,True,False
47,0.10,135427.02,0.10,42559.83,False,False
48,542.15,51743.25,0.10,35673.51,False,True
49,0.10,116983.90,45173.16,14681.50,False,False

In [9]:
dataset.columns

Index(['R&D Spend', 'Administration', 'Marketing Spend', 'Profit',
       'State_Florida', 'State_New York'],
      dtype='object')

In [10]:
independent=dataset[['R&D Spend', 'Administration', 'Marketing Spend','State_Florida', 'State_New York']]
dependent=dataset[['Profit']]

In [11]:
independent

    R&D Spend  Administration  Marketing Spend  State_Florida  State_New York
0   165349.30       136897.90        471784.20          False            True
1   162597.80       151377.69        443898.63          False           False
2   153441.61       101145.65        407934.64           True           False
3   144372.51       118671.95        383199.72          False            True
4   142107.44        91391.87        366168.52           True           False
5   131877.00        99814.81        362861.46          False            True
6   134615.56       147198.97        127716.92          False           False
7   130298.23       145530.16        323876.78           True           False
8   120542.62       148719.05        311613.39          False            True
9   123334.98       108679.27        304981.72          False           False
10  101913.18       110594.21        229161.05           True           False
11  100672.06        91790.71        249744.65          False           False
12   93863.85       127320.48        249839.54           True           False
13   91992.49       135495.17        252665.03          False           False
14  119943.34       156547.52        256513.02           True           False
15  114523.71       122616.94        261776.33          False            True
16   78013.21       121597.65        264346.16          False           False
17   94657.26       145077.68        282574.41          False            True
18   91749.26       114175.89        294919.67           True           False
19   86419.80       153514.21             0.10          False            True
20   76253.96       113867.40        298664.57          False           False
21   78389.57       153773.53        299737.39          False            True
22   73994.66       122782.85        303319.36           True           False
23   67532.63       105751.13        304768.83           True           False
24   77044.11        99281.44        140574.91          False            True
25   64664.81       139553.26        137962.72          False           False
26   75328.97       144136.08        134050.17           True           False
27   72107.70       127864.65        353183.91          False            True
28   66051.62       182645.66        118148.30           True           False
29   65605.58       153032.16        107138.48          False            True
30   61994.58       115641.38         91131.34           True           False
31   61136.48       152702.02         88218.33          False            True
32   63408.96       129219.71         46085.35          False           False
33   55494.05       103057.59        214634.91           True           False
34   46426.17       157694.02        210797.77          False           False
35   46014.12        85047.54        205517.74          False            True
36   28663.86       127056.31        201126.92           True           False
37   44070.05        51283.24        197029.52          False           False
38   20229.69        65948.03        185265.20          False            True
39   38558.61        82982.19        174999.40          False           False
40   28754.43       118546.15        172795.77          False           False
41   27893.02        84710.87        164470.81           True           False
42   23641.03        96189.73        148001.21          False           False
43   15505.83       127382.40         35534.27          False            True
44   22177.84       154806.24         28334.82          False           False
45    1000.33       124153.14          1904.03          False            True
46    1315.56       115816.31        297114.56           True           False
47       0.10       135427.02             0.10          False           False
48     542.15        51743.25             0.10          False            True
49       0.10       116983.90         45173.16          False           False

In [12]:
dependent

       Profit
0   192261.93
1   191792.16
2   191050.49
3   182902.09
4   166188.04
5   156991.22
6   156122.61
7   155752.70
8   152211.87
9   149760.06
10  146122.05
11  144259.50
12  141585.62
13  134307.45
14  132602.75
15  129917.14
16  126993.03
17  125370.47
18  124267.00
19  122776.96
20  118474.13
21  111313.12
22  110352.35
23  108734.09
24  108552.14
25  107404.44
26  105733.64
27  105008.41
28  103282.48
29  101004.74
30   99937.69
31   97483.66
32   97427.94
33   96779.02
34   96712.90
35   96479.61
36   90708.29
37   89949.24
38   81229.16
39   81005.86
40   78240.01
41   77798.93
42   71498.59
43   69759.08
44   65200.43
45   64926.18
46   49490.85
47   42559.83
48   35673.51
49   14681.50

In [15]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(independent,dependent,test_size=0.2,random_state=11)

In [16]:
x_train

    R&D Spend  Administration  Marketing Spend  State_Florida  State_New York
14  119943.34       156547.52        256513.02           True           False
42   23641.03        96189.73        148001.21          False           False
5   131877.00        99814.81        362861.46          False            True
35   46014.12        85047.54        205517.74          False            True
30   61994.58       115641.38         91131.34           True           False
9   123334.98       108679.27        304981.72          False           False
43   15505.83       127382.40         35534.27          False            True
39   38558.61        82982.19        174999.40          False           False
49       0.10       116983.90         45173.16          False           False
21   78389.57       153773.53        299737.39          False            True
15  114523.71       122616.94        261776.33          False            True
0   165349.30       136897.90        471784.20          False            True
23   67532.63       105751.13        304768.83           True           False
41   27893.02        84710.87        164470.81           True           False
11  100672.06        91790.71        249744.65          False           False
6   134615.56       147198.97        127716.92          False           False
3   144372.51       118671.95        383199.72          False            True
31   61136.48       152702.02         88218.33          False            True
29   65605.58       153032.16        107138.48          False            True
40   28754.43       118546.15        172795.77          False           False
47       0.10       135427.02             0.10          False           False
46    1315.56       115816.31        297114.56           True           False
20   76253.96       113867.40        298664.57          False           False
10  101913.18       110594.21        229161.05           True           False
1   162597.80       151377.69        443898.63          False           False
44   22177.84       154806.24         28334.82          False           False
34   46426.17       157694.02        210797.77          False           False
4   142107.44        91391.87        366168.52           True           False
32   63408.96       129219.71         46085.35          False           False
28   66051.62       182645.66        118148.30           True           False
24   77044.11        99281.44        140574.91          False            True
18   91749.26       114175.89        294919.67           True           False
7   130298.23       145530.16        323876.78           True           False
33   55494.05       103057.59        214634.91           True           False
12   93863.85       127320.48        249839.54           True           False
13   91992.49       135495.17        252665.03          False           False
17   94657.26       145077.68        282574.41          False            True
27   72107.70       127864.65        353183.91          False            True
16   78013.21       121597.65        264346.16          False           False
25   64664.81       139553.26        137962.72          False           False

In [17]:
y_train

       Profit
14  132602.75
42   71498.59
5   156991.22
35   96479.61
30   99937.69
9   149760.06
43   69759.08
39   81005.86
49   14681.50
21  111313.12
15  129917.14
0   192261.93
23  108734.09
41   77798.93
11  144259.50
6   156122.61
3   182902.09
31   97483.66
29  101004.74
40   78240.01
47   42559.83
46   49490.85
20  118474.13
10  146122.05
1   191792.16
44   65200.43
34   96712.90
4   166188.04
32   97427.94
28  103282.48
24  108552.14
18  124267.00
7   155752.70
33   96779.02
12  141585.62
13  134307.45
17  125370.47
27  105008.41
16  126993.03
25  107404.44

In [18]:
x_test

    R&D Spend  Administration  Marketing Spend  State_Florida  State_New York
37   44070.05        51283.24        197029.52          False           False
45    1000.33       124153.14          1904.03          False            True
36   28663.86       127056.31        201126.92           True           False
22   73994.66       122782.85        303319.36           True           False
2   153441.61       101145.65        407934.64           True           False
48     542.15        51743.25             0.10          False            True
26   75328.97       144136.08        134050.17           True           False
38   20229.69        65948.03        185265.20          False            True
8   120542.62       148719.05        311613.39          False            True
19   86419.80       153514.21             0.10          False            True

In [19]:
y_test

       Profit
37   89949.24
45   64926.18
36   90708.29
22  110352.35
2   191050.49
48   35673.51
26  105733.64
38   81229.16
8   152211.87
19  122776.96

In [20]:
from sklearn.linear_model import LinearRegression

In [21]:
regressor=LinearRegression() 
regressor.fit(x_train,y_train)

LinearRegression()

In [22]:
y_pred=regressor.predict(x_test)
y_pred

array([[ 90219.0310457 ],
       [ 44226.53149439],
       [ 73160.4917566 ],
       [113415.75987271],
       [182628.69818789],
       [ 46841.15865196],
       [109227.48565635],
       [ 67305.57632987],
       [149922.12110837],
       [113463.24511432]])

In [23]:
from sklearn.metrics import r2_score
r2score=r2_score(y_test,y_pred)

In [24]:
r2score

0.92869462583268

In [25]:
import pickle
filename="MLR.sav"
pickle.dump(regressor,open(filename,'wb'))

In [27]:
loaded_model=pickle.load(open("MLR.sav",'rb'))
result=loaded_model.predict([[1000,2000,3000,4000,5000]])

C:\Users\Gayathri R\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

In [28]:
result

array([[-16548563.09551293]])

In [30]:
dataset.columns

Index(['R&D Spend', 'Administration', 'Marketing Spend', 'Profit',
       'State_Florida', 'State_New York'],
      dtype='object')

In [32]:
RD=float(input("enter the R&D Spend'"))
AD=float(input("enter the 'Administration',"))
MS=float(input("enter the 'Marketing Spend'"))
SF=float(input("enter the 'State_Florida'"))
SNY=float(input("enter the 'State_New York'"))
result=loaded_model.predict([[RD,AD,MS,SF,SNY]])
result

enter the R&D Spend' 600000
enter the 'Administration', 70000
enter the 'Marketing Spend' 80000
enter the 'State_Florida' 0
enter the 'State_New York' 1

C:\Users\Gayathri R\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([[543044.40123733]])