In [17]:
import pandas as pd

In [18]:
dataset=pd.read_csv("customer_data.csv")

In [19]:
dataset

,name,age,gender,education,income,country,purchase_frequency,spending
0,Teresa Williams MD,42,Female,High School,53936,Slovenia,0.9,13227.120
1,Christine Myers,49,Female,Master,82468,Aruba,0.6,12674.040
2,Dwayne Moreno,55,Male,Bachelor,56941,Cyprus,0.3,5354.115
3,Amy Norton,24,Female,Bachelor,60651,Palau,0.2,2606.510
4,Tonya Adams,64,Male,Master,81884,Zambia,0.9,18984.780
...,...,...,...,...,...,...,...,...
995,Jason Haas,42,Female,PhD,98170,Bosnia and Herzegovina,0.7,17435.950
996,Sharon Valdez,39,Male,High School,59174,Eritrea,0.9,11662.830
997,Andrew Taylor,50,Male,Master,59808,Serbia,0.4,7196.160
998,Jessica Johnson,50,Female,Master,58272,Cyprus,0.7,13939.520
999,Brian Williams,38,Female,Bachelor,32512,Turkey,0.5,8312.800

In [20]:
dataset.columns

Index(['name', 'age', 'gender', 'education', 'income', 'country',
       'purchase_frequency', 'spending'],
      dtype='object')

In [21]:
dataset

,name,age,gender,education,income,country,purchase_frequency,spending
0,Teresa Williams MD,42,Female,High School,53936,Slovenia,0.9,13227.120
1,Christine Myers,49,Female,Master,82468,Aruba,0.6,12674.040
2,Dwayne Moreno,55,Male,Bachelor,56941,Cyprus,0.3,5354.115
3,Amy Norton,24,Female,Bachelor,60651,Palau,0.2,2606.510
4,Tonya Adams,64,Male,Master,81884,Zambia,0.9,18984.780
...,...,...,...,...,...,...,...,...
995,Jason Haas,42,Female,PhD,98170,Bosnia and Herzegovina,0.7,17435.950
996,Sharon Valdez,39,Male,High School,59174,Eritrea,0.9,11662.830
997,Andrew Taylor,50,Male,Master,59808,Serbia,0.4,7196.160
998,Jessica Johnson,50,Female,Master,58272,Cyprus,0.7,13939.520
999,Brian Williams,38,Female,Bachelor,32512,Turkey,0.5,8312.800

In [22]:
dataset=pd.get_dummies(dataset,drop_first=True)

In [23]:
dataset

,age,income,purchase_frequency,spending,name_Aaron Martin,name_Abigail Hood,name_Abigail Shaw,name_Adam Frazier,name_Adam Murray,name_Adam Nelson,...,country_Uruguay,country_Uzbekistan,country_Vanuatu,country_Venezuela,country_Vietnam,country_Wallis and Futuna,country_Western Sahara,country_Yemen,country_Zambia,country_Zimbabwe
0,42,53936,0.9,13227.120,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,49,82468,0.6,12674.040,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,55,56941,0.3,5354.115,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,24,60651,0.2,2606.510,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,64,81884,0.9,18984.780,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,42,98170,0.7,17435.950,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
996,39,59174,0.9,11662.830,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
997,50,59808,0.4,7196.160,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
998,50,58272,0.7,13939.520,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
999,38,32512,0.5,8312.800,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False